import { AlertCircle, Building2, CalendarCheck, CheckCircle2, CircleDollarSign, Clock3 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { AdminKpiCard, AdminMetricStrip } from '../../components/admin/AdminVisualSystem'
import { AdminPageHeader } from '../../components/admin/AdminPageHeader'
import { CompanyLogo } from '../../components/admin/CompanyLogo'
import { adminRepository } from '../../repositories'
import type { RedComercialDashboardData } from '../../types/admin'
import { getOpportunityFinancialCue, getOpportunityPresentation } from '../opportunity-status'
import { isRedComercialAdmin } from '../red-comercial-utils'
import { useAdminAuth } from '../useAdminAuth'

const emptyData: RedComercialDashboardData = { summary: { followups_today: 0, followups_overdue: 0, active_prospects: 0, opportunities_in_process: 0, opportunities_arista: 0, payments_pending: 0, won_this_month: 0, commission_pending: 0 }, attention_today: [], upcoming_followups: [], opportunities: [], cross_opportunities: [], recent_results: [], portfolios: [], recent_activity: [] }
const labels: Record<string, string> = { won: 'Ganada', lost: 'Perdida', in_process: 'En proceso', pending: 'Pendiente', signed: 'Firmado', detected: 'Detectada', under_review: 'En revisión', assigned: 'Asignada', collaborator: 'Colaborador', arista: 'Arista', shared: 'Compartida' }
function label(value: string) { return labels[value] ?? 'Sin definir' }
function date(value: string | null | undefined) { return value ? new Intl.DateTimeFormat('es-CL', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : 'Sin fecha' }
function money(value: number | null | undefined, currency: string) { return value == null ? 'Sin definir' : new Intl.NumberFormat('es-CL', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value) }
function Empty({ text }: { text: string }) { return <p className="py-2 text-[12px] text-slate-500">{text}</p> }
function Rows({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-[12px]"><tbody>{children}</tbody></table></div> }
function Badge({ kind, value }: { kind: 'payment' | 'commission'; value: string }) { const presentation = getOpportunityPresentation(kind, value); return <span className={`inline-flex rounded-full border px-2 py-1 text-[10px] font-semibold ${presentation.className}`}>{presentation.label}</span> }
function participation(item: RedComercialDashboardData['opportunities'][number]) { if (item.collaborator_compensation_type === 'percentage' && item.collaborator_compensation_rate != null) return `${item.collaborator_compensation_rate}%`; if (item.collaborator_compensation_type === 'fixed_amount' && item.collaborator_compensation_amount != null && item.currency) return money(item.collaborator_compensation_amount, item.currency); return 'Sin definir' }

type ActivityItem = RedComercialDashboardData['recent_activity'][number] & { change_count?: number }
function groupedActivity(items: RedComercialDashboardData['recent_activity']): ActivityItem[] {
  const important = (item: ActivityItem) => /handoff|entregada|contrato|pago|comision|participacion|ganada|perdida|cruzada|convertida/i.test(`${item.activity_type} ${item.title}`)
  return items.reduce<ActivityItem[]>((groups, item) => {
    const previous = groups[groups.length - 1]
    const sameWindow = previous && !important(item) && !important(previous) && previous.prospect_name === item.prospect_name && previous.created_by_name === item.created_by_name && previous.activity_type === item.activity_type && Math.abs(new Date(previous.created_at).getTime() - new Date(item.created_at).getTime()) <= 10 * 60 * 1000
    if (sameWindow) { previous.change_count = (previous.change_count ?? 1) + 1; return groups }
    groups.push({ ...item, change_count: 1 })
    return groups
  }, [])
}

export function RedComercialDashboardPage() {
  const admin = isRedComercialAdmin(useAdminAuth().profile)
  const [data, setData] = useState<RedComercialDashboardData>(emptyData)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; void adminRepository.getRedComercialDashboard('today').then((result) => { if (!active) return; setData(result.data ?? emptyData); setError(result.error ?? '') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  const summary = data.summary
  const activities = groupedActivity(data.recent_activity).slice(0, 8)
  return <div className="grid gap-3">
    <AdminPageHeader eyebrow="RED COMERCIAL / INICIO" title="Red Comercial Arista" text="Resumen operativo de tu actividad comercial." />
    {error && <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-[12px] text-red-800">No fue posible cargar el dashboard.</div>}
    {loading ? <div className="rounded-lg border border-[#ddd6ca] bg-white px-3 py-4 text-[12px] text-slate-500">Cargando resumen operativo...</div> : <>
      <section className="grid grid-cols-2 gap-2 lg:grid-cols-6">
        <AdminKpiCard label={admin ? 'Seguimientos hoy' : 'Mis seguimientos hoy'} value={summary.followups_today} icon={CalendarCheck} tone="process" />
        <AdminKpiCard label={admin ? 'Seguimientos vencidos' : 'Mis vencidos'} value={summary.followups_overdue} icon={AlertCircle} tone="negative" />
        <AdminKpiCard label={admin ? 'Oportunidades en proceso' : 'Mis oportunidades en proceso'} value={summary.opportunities_in_process} icon={Clock3} tone="process" />
        <AdminKpiCard label={admin ? 'Gestión entregada a Arista' : 'Entregadas a Arista'} value={summary.opportunities_arista} icon={Building2} tone="neutral" />
        <AdminKpiCard label={admin ? 'Pagos pendientes' : 'Participaciones pendientes'} value={admin ? summary.payments_pending : summary.commission_pending} icon={CircleDollarSign} tone="pending" />
        <AdminKpiCard label={admin ? 'Ganadas este mes' : 'Prospectos activos'} value={admin ? summary.won_this_month : summary.active_prospects} icon={CheckCircle2} tone="positive" />
      </section>
      <AdminMetricStrip><span>Atención prioritaria <strong className="text-slate-900">{data.attention_today.length}</strong></span><span>Próximos seguimientos <strong className="text-slate-900">{data.upcoming_followups.length}</strong></span><span>Oportunidades cruzadas <strong className="text-slate-900">{data.cross_opportunities.length}</strong></span><span>Actividad reciente <strong className="text-slate-900">{activities.length}</strong></span></AdminMetricStrip>
      <div className="dashboard-columns">
        <div className="dashboard-column">
          <DashboardPanel title="Atención hoy" className="dashboard-order-attention">{data.attention_today.length === 0 ? <Empty text="Todo al día." /> : <Rows>{data.attention_today.map((item) => <tr key={`${item.type}-${item.prospect_id}-${item.at}`} className="border-b border-[#f1ece3] last:border-0"><td className="px-2 py-1.5"><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-800">{item.label}</span></td><td className="px-2 py-1.5 font-semibold"><Link to={item.href} className="hover:text-[#235b3e]">{item.prospect_name}</Link><div className="text-[11px] font-normal text-slate-500">{item.company_name}</div></td><td className="px-2 py-1.5 text-slate-600">{item.reason}</td><td className="whitespace-nowrap px-2 py-1.5 text-slate-500">{date(item.at)}</td></tr>)}</Rows>}</DashboardPanel>
          <DashboardSection className="dashboard-order-followups" title="Próximos seguimientos" href="/admin/seguimientos" link="Ver todos los seguimientos →">{data.upcoming_followups.length === 0 ? <Empty text="No hay seguimientos próximos." /> : <Rows>{data.upcoming_followups.map((item) => <tr key={item.prospect_id} className="border-b border-[#f1ece3] last:border-0"><td className="px-2 py-1.5 font-semibold"><Link to={item.href}>{item.prospect_name}</Link><div className="text-[11px] font-normal text-slate-500">{item.company_name}</div></td><td className="px-2 py-1.5">{item.status === 'today' ? 'Hoy' : 'Próximo'}</td><td className="px-2 py-1.5 text-slate-500">{date(item.at)}</td></tr>)}</Rows>}</DashboardSection>
          <DashboardSection className="dashboard-order-cross" title="Oportunidades cruzadas recientes" href="/admin/oportunidades-cruzadas" link="Ver oportunidades →">{data.cross_opportunities.length === 0 ? <Empty text="Sin oportunidades cruzadas nuevas." /> : <Rows>{data.cross_opportunities.map((item) => <tr key={item.id} className="border-b border-[#f1ece3] last:border-0"><td className="px-2 py-1.5 font-semibold">{item.prospect_name}<div className="text-[11px] font-normal text-slate-500">Destino: {item.target_company_name}</div></td><td className="px-2 py-1.5">{label(item.status)}</td><td className="px-2 py-1.5 text-slate-500">{item.detected_by_name || 'Sin detector'}</td></tr>)}</Rows>}</DashboardSection>
          <section className="dashboard-panel dashboard-order-portfolios rounded-lg border border-[#ddd6ca] bg-white p-2.5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-[#17202d]">Carteras</h2><Link to="/admin/prospectos" className="text-[11px] font-semibold text-[#235b3e]">Ver prospectos →</Link></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{data.portfolios.slice(0, 6).map((item) => <Link key={item.id} to={item.href} className="flex min-w-0 items-center gap-2 rounded-md border border-[#eee8dd] p-2 transition hover:border-[#235b3e] hover:bg-[#fbfaf7]"><CompanyLogo company={{ name: item.name, logo_storage_path: item.logo_storage_path }} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate text-[12px] text-[#17202d]">{item.name}</strong><span className="block text-[11px] text-slate-500">{item.active_prospects} prospectos · {item.overdue} vencidos · {item.opportunities_in_process} oportunidades</span></span></Link>)}</div>{data.portfolios.length === 0 && <Empty text="No hay carteras disponibles." />}</section>
        </div>
        <div className="dashboard-column">
          <DashboardPanel title="Actividad reciente" className="dashboard-order-activity"><div className="max-h-[370px] overflow-y-auto pr-1">{activities.length === 0 ? <Empty text="Sin actividad reciente." /> : <div className="grid gap-1">{activities.map((item) => <div key={item.id} className="flex gap-2 border-b border-[#f1ece3] py-1.5 last:border-0"><span className="mt-0.5 inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#e7f0ea] text-[#235b3e]"><Clock3 size={13} /></span><div className="min-w-0"><p className="truncate text-[12px] font-semibold text-[#17202d]">{item.title}</p><p className="text-[11px] text-slate-500">{item.prospect_name} · {item.created_by_name || 'Red Comercial'} · {item.change_count && item.change_count > 1 ? `${item.change_count} cambios · ` : ''}{date(item.created_at)}</p></div></div>)}</div>}</div></DashboardPanel>
          <DashboardSection className="dashboard-order-opportunities" title="Oportunidades en curso" href="/admin/oportunidades" link="Ver oportunidades →">{data.opportunities.length === 0 ? <Empty text="Sin oportunidades recientes." /> : <Rows>{data.opportunities.map((item) => { const cue = getOpportunityFinancialCue(item.payment_status, item.commission_status ?? ''); return <tr key={item.id} className={`border-b border-[#f1ece3] last:border-0 ${cue.rowClassName}`}><td className="px-2 py-1.5 font-semibold"><Link to={item.href}>{item.prospect_name}</Link><div className="text-[11px] font-normal text-slate-500">{item.company_name}</div></td>{admin ? <><td className="px-2 py-1.5">{label(item.control_mode)}</td><td className="px-2 py-1.5"><Badge kind="payment" value={item.payment_status} /></td><td className="px-2 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Contrato</span><div className="mt-0.5">{getOpportunityPresentation('contract', item.contract_status).label}</div></td></> : <><td className="px-2 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Pago cliente</span><div className="mt-0.5"><Badge kind="payment" value={item.payment_status} /></div></td><td className="px-2 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Mi participación</span><div className="mt-0.5">{item.commission_status ? <><Badge kind="commission" value={item.commission_status} />{item.collaborator_compensation_type && <div className="mt-1 text-[10px] font-semibold text-slate-600">{participation(item)}</div>}</> : <span className="text-[10px] font-semibold text-slate-500">Sin información</span>}</div></td><td className="px-2 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Control</span><div className="mt-0.5">{getOpportunityPresentation('control', item.control_mode).label}</div></td><td className="px-2 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Contrato</span><div className="mt-0.5">{getOpportunityPresentation('contract', item.contract_status).label}</div></td></>}</tr>})}</Rows>}</DashboardSection>
          <DashboardSection className="dashboard-order-results" title="Resultados recientes" href="/admin/resultados" link="Ver resultados →">{data.recent_results.length === 0 ? <Empty text="Sin cierres recientes." /> : <Rows>{data.recent_results.map((item) => <tr key={item.id} className="border-b border-[#f1ece3] last:border-0"><td className="px-2 py-1.5 font-semibold">{item.prospect_name}<div className="text-[11px] font-normal text-slate-500">{item.company_name}</div></td><td className={`px-2 py-1.5 font-semibold ${item.result_status === 'won' ? 'text-emerald-700' : 'text-rose-700'}`}>{label(item.result_status)}</td><td className="px-2 py-1.5 text-slate-500">{date(item.closed_at)}</td><td className="px-2 py-1.5 text-slate-500">{item.collaborator_name || 'Sin atribución'}</td></tr>)}</Rows>}</DashboardSection>
        </div>
      </div>
    </>}
  </div>
}

function DashboardPanel({ title, className = '', children }: { title: string; className?: string; children: React.ReactNode }) { return <section className={`dashboard-panel rounded-lg border border-[#ddd6ca] bg-white p-2.5 ${className}`}><h2 className="text-sm font-semibold text-[#17202d]">{title}</h2>{children}</section> }
function DashboardSection({ title, href, link, className = '', children }: { title: string; href: string; link: string; className?: string; children: React.ReactNode }) { return <section className={`dashboard-panel rounded-lg border border-[#ddd6ca] bg-white p-2.5 ${className}`}><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold text-[#17202d]">{title}</h2><Link to={href} className="text-[11px] font-semibold text-[#235b3e]">{link}</Link></div>{children}</section> }
