import { BarChart3, CheckCircle2, CircleDollarSign, XCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CompanyLogo } from '../../components/admin/CompanyLogo'
import { EmptyState } from '../../components/admin/EmptyState'
import { AdminKpiCard, AdminMetricStrip, AdminTabs } from '../../components/admin/AdminVisualSystem'
import { adminRepository } from '../../repositories'
import type { RedComercialClosure, RedComercialResultsData, RedComercialResultsFilters, RepresentedCompanyRecord, CollaboratorRecord, RedComercialProspectDetailRecord } from '../../types/admin'
import { isRedComercialAdmin } from '../red-comercial-utils'
import { useAdminAuth } from '../useAdminAuth'
import { ProspectDetailPanel } from './RedComercialProspectsPage'

const emptyData: RedComercialResultsData = { summary: { closures: 0, won: 0, lost: 0, cancelled: 0, in_process: 0, paid: 0, payment_pending: 0, commission_pending: 0, close_rate: null, avg_close_days: null }, volume_by_currency: {}, companies: [], collaborators: [], closures: [], total_closures: 0 }

function dateLabel(value: string | null) { return value ? new Intl.DateTimeFormat('es-CL', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)) : 'Sin fecha' }
function money(value: number | null | undefined, currency: string) { return value == null ? 'Sin definir' : new Intl.NumberFormat('es-CL', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value) }
function currencies(values: Record<string, number>) { return Object.entries(values).map(([currency, value]) => `${currency} ${new Intl.NumberFormat('es-CL', { maximumFractionDigits: 0 }).format(value)}`).join(' · ') || 'Sin ventas ganadas'
}

function periodRange(period: string) {
  const now = new Date(); const from = new Date(now); const to = new Date(now)
  if (period === 'month') from.setDate(1)
  if (period === '30d') from.setDate(from.getDate() - 29)
  if (period === 'quarter') { from.setMonth(Math.floor(from.getMonth() / 3) * 3, 1) }
  if (period === 'year') from.setMonth(0, 1)
  if (period === 'all') return { from: undefined, to: undefined }
  to.setHours(23, 59, 59, 999); from.setHours(0, 0, 0, 0)
  return { from: from.toISOString(), to: to.toISOString() }
}

export function RedComercialResultsPage() {
  const auth = useAdminAuth(); const admin = isRedComercialAdmin(auth.profile); const [params] = useSearchParams()
  const [period, setPeriod] = useState(params.get('period') || 'month'); const [data, setData] = useState(emptyData); const [companies, setCompanies] = useState<RepresentedCompanyRecord[]>([]); const [collaborators, setCollaborators] = useState<CollaboratorRecord[]>([]); const [tab, setTab] = useState<'summary' | 'companies' | 'collaborators' | 'closures'>(admin ? 'summary' : 'summary'); const [filters, setFilters] = useState<RedComercialResultsFilters>({ companyId: params.get('company') || '', resultStatus: '', paymentStatus: '', controlMode: '', page: 1, pageSize: 25 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<{ row: RedComercialClosure; prospect: RedComercialProspectDetailRecord } | null>(null)

  useEffect(() => { let alive = true; void (async () => { const companyResult = admin ? await adminRepository.listRepresentedCompanies() : await adminRepository.listMyRepresentedCompanies(); const collaboratorResult = admin ? await adminRepository.listCollaborators() : { data: [], error: null }; if (!alive) return; setCompanies((companyResult.data ?? []).filter((item) => item.status === 'active')); setCollaborators(collaboratorResult.data ?? []) })(); return () => { alive = false } }, [admin])
  useEffect(() => { let alive = true; setLoading(true); setError(''); const range = period === 'custom' ? { from: filters.from, to: filters.to } : periodRange(period); void adminRepository.getRedComercialResults({ ...filters, ...range }).then((result) => { if (!alive) return; setData(result.data ?? emptyData); setError(result.error ?? '') }).finally(() => { if (alive) setLoading(false) }); return () => { alive = false } }, [filters, period])
  async function openClosure(row: RedComercialClosure) { const result = await adminRepository.getRedComercialProspectDetail(row.prospect_id); if (result.data) setSelected({ row, prospect: result.data }); else setError(result.error ?? 'No fue posible abrir el cierre.') }
  const summary = data.summary; const maxStatus = Math.max(summary.won, summary.lost, summary.in_process, summary.cancelled, 1)
  const tabs = admin ? [['summary', 'Resumen'], ['companies', 'Empresas Arista'], ['collaborators', 'Colaboradores'], ['closures', 'Cierres']] as const : [['summary', 'Resumen'], ['closures', 'Mis cierres']] as const
  const closureRows = useMemo(() => data.closures, [data.closures])

  return <div className="grid min-w-0 gap-3">
    <header className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#235b3e]">Red Comercial / Resultados</p><h1 className="mt-1 text-[26px] font-semibold leading-tight text-[#17202d]">{admin ? 'Resultados' : 'Mis resultados'}</h1><p className="text-[13px] text-slate-600">Rendimiento comercial, cierres y resultados de la Red Comercial Arista.</p></div><label className="grid gap-1 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-500">Periodo<select value={period} onChange={(event) => { setPeriod(event.target.value); setFilters((current) => ({ ...current, page: 1 })) }} className="h-9 rounded-md border border-[#c9c1b4] bg-white px-2.5 text-[13px] font-normal normal-case tracking-normal"><option value="month">Este mes</option><option value="30d">Últimos 30 días</option><option value="quarter">Este trimestre</option><option value="year">Este año</option><option value="all">Todo el periodo</option><option value="custom">Personalizado</option></select></label></header>
    {period === 'custom' && <div className="flex flex-wrap gap-2 rounded-lg border border-[#ddd6ca] bg-white p-2"><input aria-label="Desde" type="date" onChange={(event) => setFilters((current) => ({ ...current, from: event.target.value ? `${event.target.value}T00:00:00.000Z` : undefined, page: 1 }))} /><input aria-label="Hasta" type="date" onChange={(event) => setFilters((current) => ({ ...current, to: event.target.value ? `${event.target.value}T23:59:59.999Z` : undefined, page: 1 }))} /></div>}
    <section className="grid grid-cols-2 gap-2 lg:grid-cols-6"><AdminKpiCard label="Cierres" value={summary.closures} tone="neutral" icon={BarChart3} /><AdminKpiCard label="Ganadas" value={summary.won} tone="positive" icon={CheckCircle2} /><AdminKpiCard label="Perdidas" value={summary.lost} tone="negative" icon={XCircle} /><AdminKpiCard label="Tasa de cierre" value={summary.close_rate == null ? '—' : `${summary.close_rate}%`} tone="process" icon={BarChart3} /><AdminKpiCard label="Volumen vendido" value={currencies(data.volume_by_currency)} tone="pending" icon={CircleDollarSign} /><AdminKpiCard label="Pagadas" value={summary.paid} tone="collaborator" icon={CheckCircle2} /></section>
    <AdminMetricStrip><span>En proceso <strong className="text-slate-900">{summary.in_process}</strong></span><span>Pago pendiente <strong className="text-slate-900">{summary.payment_pending}</strong></span><span>Comisión pendiente <strong className="text-slate-900">{summary.commission_pending}</strong></span><span>Tiempo medio <strong className="text-slate-900">{summary.avg_close_days == null ? '—' : `${summary.avg_close_days} días`}</strong></span></AdminMetricStrip>
    <AdminTabs items={tabs.map(([key, label]) => ({ key, label }))} active={tab} onChange={(key) => setTab(key as typeof tab)} />
    <section className="grid grid-cols-1 gap-2 rounded-lg border border-[#ddd6ca] bg-white p-2 lg:grid-cols-[1fr_180px_150px_150px_150px]"><input placeholder="Buscar empresa o prospecto..." value={filters.search ?? ''} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value, page: 1 }))} className="h-9 rounded-md border border-[#c9c1b4] px-3 text-[13px]" /><select aria-label="Empresa Arista" value={filters.companyId ?? ''} onChange={(event) => setFilters((current) => ({ ...current, companyId: event.target.value, page: 1 }))} className="h-9 rounded-md border border-[#c9c1b4] px-2 text-[13px]"><option value="">Todas las empresas</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select>{admin && <select aria-label="Colaborador" value={filters.collaboratorId ?? ''} onChange={(event) => setFilters((current) => ({ ...current, collaboratorId: event.target.value, page: 1 }))} className="h-9 rounded-md border border-[#c9c1b4] px-2 text-[13px]"><option value="">Todos los colaboradores</option>{collaborators.map((collaborator) => <option key={collaborator.id} value={collaborator.id}>{collaborator.full_name}</option>)}</select>}<select aria-label="Resultado" value={filters.resultStatus ?? ''} onChange={(event) => setFilters((current) => ({ ...current, resultStatus: event.target.value, page: 1 }))} className="h-9 rounded-md border border-[#c9c1b4] px-2 text-[13px]"><option value="">Todos los resultados</option><option value="won">Ganadas</option><option value="lost">Perdidas</option><option value="cancelled">Canceladas</option><option value="in_process">En proceso</option></select><select aria-label="Pago" value={filters.paymentStatus ?? ''} onChange={(event) => setFilters((current) => ({ ...current, paymentStatus: event.target.value, page: 1 }))} className="h-9 rounded-md border border-[#c9c1b4] px-2 text-[13px]"><option value="">Todos los pagos</option><option value="paid">Pagado</option><option value="pending">Pendiente</option><option value="partial">Parcial</option><option value="overdue">Vencido</option></select></section>
    {loading ? <div className="rounded-lg border border-[#ddd6ca] bg-white p-4 text-sm text-slate-500">Cargando resultados...</div> : error ? <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">No fue posible cargar los resultados.</div> : tab === 'summary' ? <div className="grid gap-3 lg:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]"><section className="rounded-lg border border-[#ddd6ca] bg-white p-3"><h2 className="text-sm font-semibold text-[#17202d]">Estado de cierres</h2><div className="mt-3 grid gap-2 text-[12px]">{[['Ganadas', summary.won, 'bg-emerald-500'], ['Perdidas', summary.lost, 'bg-rose-400'], ['En proceso', summary.in_process, 'bg-sky-400'], ['Canceladas', summary.cancelled, 'bg-slate-400']].map(([label, value, color]) => <div key={String(label)} className="grid grid-cols-[90px_1fr_30px] items-center gap-2"><span>{label}</span><span className="h-2 rounded-full bg-slate-100"><span className={`block h-2 rounded-full ${color}`} style={{ width: `${(Number(value) / maxStatus) * 100}%` }} /></span><strong>{value}</strong></div>)}</div><h2 className="mt-5 text-sm font-semibold text-[#17202d]">Volumen vendido</h2><p className="mt-1 text-[13px] text-slate-600">{currencies(data.volume_by_currency)}</p></section><section className="rounded-lg border border-[#ddd6ca] bg-white p-3"><h2 className="text-sm font-semibold text-[#17202d]">Cierres recientes</h2><ClosureTable rows={closureRows.slice(0, 5)} admin={admin} onOpen={openClosure} /></section></div> : tab === 'companies' ? <CompanyTable rows={data.companies} /> : tab === 'collaborators' ? <CollaboratorTable rows={data.collaborators} /> : <section className="rounded-lg border border-[#ddd6ca] bg-white"><ClosureTable rows={closureRows} admin={admin} onOpen={openClosure} /><div className="flex items-center justify-between border-t border-[#eee8dd] px-3 py-2 text-[12px] text-slate-600"><span>{data.total_closures} cierres</span><div className="flex items-center gap-2"><select value={filters.pageSize ?? 25} onChange={(event) => setFilters((current) => ({ ...current, pageSize: Number(event.target.value), page: 1 }))} className="rounded border border-[#c9c1b4] px-2 py-1">{[25, 50, 100].map((size) => <option key={size}>{size}</option>)}</select><button type="button" disabled={(filters.page ?? 1) <= 1} onClick={() => setFilters((current) => ({ ...current, page: (current.page ?? 1) - 1 }))}>Anterior</button><span>Página {filters.page ?? 1}</span><button type="button" disabled={(filters.page ?? 1) * (filters.pageSize ?? 25) >= data.total_closures} onClick={() => setFilters((current) => ({ ...current, page: (current.page ?? 1) + 1 }))}>Siguiente</button></div></div></section>}
    {!loading && !error && tab !== 'summary' && tab !== 'companies' && tab !== 'collaborators' && closureRows.length === 0 && <EmptyState title="Sin resultados para este periodo" text="Prueba otro periodo o ajusta los filtros." />}
    {selected && <ProspectDetailPanel prospect={selected.prospect} opportunityId={selected.row.id} onClose={() => setSelected(null)} onChanged={() => { void adminRepository.getRedComercialResults(filters).then((result) => { if (result.data) setData(result.data) }) }} />}
  </div>
}

function ClosureTable({ rows, admin, onOpen }: { rows: RedComercialClosure[]; admin: boolean; onOpen: (row: RedComercialClosure) => void }) {
  if (!rows.length) return <p className="py-5 text-[12px] text-slate-500">Sin cierres en este periodo.</p>
  return <div className="mt-2 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[12px]"><thead className="text-[10px] uppercase tracking-[.08em] text-slate-500"><tr>{['Empresa', 'Cliente', 'Resultado', 'Colaborador', 'Venta neta', 'Pago', 'Fecha'].map((item) => <th key={item} className="border-b border-[#eee8dd] px-2 py-2">{item}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} onClick={() => onOpen(row)} className="cursor-pointer hover:bg-[#f7faf7]"><td className="px-2 py-2 font-semibold">{row.company_name}</td><td className="px-2 py-2">{row.prospect_name}</td><td className={row.result_status === 'won' ? 'px-2 py-2 text-emerald-700' : 'px-2 py-2 text-rose-700'}>{row.result_status === 'won' ? 'Ganada' : 'Perdida'}</td><td className="px-2 py-2">{row.collaborator_name || 'Sin atribución'}</td><td className="px-2 py-2">{admin ? money(row.sale_net_amount, row.currency) : '—'}</td><td className="px-2 py-2">{row.payment_status}</td><td className="px-2 py-2">{dateLabel(row.closed_at)}</td></tr>)}</tbody></table></div>
}

function CompanyTable({ rows }: { rows: RedComercialResultsData['companies'] }) { return <section className="overflow-x-auto rounded-lg border border-[#ddd6ca] bg-white"><table className="w-full min-w-[900px] text-left text-[12px]"><thead className="bg-[#fbfaf7] text-[10px] uppercase tracking-[.08em] text-slate-500"><tr>{['Empresa', 'Cerradas', 'Ganadas', 'Perdidas', 'Tasa', 'En proceso', 'Volumen vendido', 'Pagadas', 'Pago pendiente'].map((item) => <th key={item} className="border-b border-[#eee8dd] px-2.5 py-2">{item}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.company_id} className="border-b border-[#f1ece3]"><td className="px-2.5 py-2 font-semibold"><span className="inline-flex items-center gap-2"><CompanyLogo company={{ name: row.company_name, logo_storage_path: row.company_logo_storage_path }} size="xs" />{row.company_name}</span></td><td className="px-2.5 py-2">{row.closed}</td><td className="px-2.5 py-2 text-emerald-700">{row.won}</td><td className="px-2.5 py-2 text-rose-700">{row.lost}</td><td className="px-2.5 py-2">{row.closed ? `${Math.round((row.won / row.closed) * 100)}%` : '—'}</td><td className="px-2.5 py-2">{row.in_process}</td><td className="px-2.5 py-2">{currencies(row.volume_by_currency)}</td><td className="px-2.5 py-2">{row.paid}</td><td className="px-2.5 py-2">{row.payment_pending}</td></tr>)}</tbody></table></section> }
function CollaboratorTable({ rows }: { rows: RedComercialResultsData['collaborators'] }) { return <section className="overflow-x-auto rounded-lg border border-[#ddd6ca] bg-white"><table className="w-full min-w-[850px] text-left text-[12px]"><thead className="bg-[#fbfaf7] text-[10px] uppercase tracking-[.08em] text-slate-500"><tr>{['Colaborador', 'Atribuidas', 'Cerradas', 'Ganadas', 'Perdidas', 'Tasa', 'Generada', 'Pendiente', 'Pagada'].map((item) => <th key={item} className="border-b border-[#eee8dd] px-2.5 py-2">{item}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.collaborator_id} className="border-b border-[#f1ece3]"><td className="px-2.5 py-2 font-semibold">{row.collaborator_name || 'Sin nombre'}</td><td className="px-2.5 py-2">{row.attributed}</td><td className="px-2.5 py-2">{row.closed}</td><td className="px-2.5 py-2 text-emerald-700">{row.won}</td><td className="px-2.5 py-2 text-rose-700">{row.lost}</td><td className="px-2.5 py-2">{row.closed ? `${Math.round((row.won / row.closed) * 100)}%` : '—'}</td><td className="px-2.5 py-2">{row.generated}</td><td className="px-2.5 py-2">{row.pending}</td><td className="px-2.5 py-2">{row.paid}</td></tr>)}</tbody></table></section> }
